[toolchain]
anchor_version = "1.0.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
certigrid_program = "Certi111111111111111111111111111111111111111"

[programs.devnet]
certigrid_program = "Certi111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"
